AandB1.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 1
AandB2.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 1
AandB3.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 1
AandB4.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 1
AandB5.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 1
AandB6.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 2
AandB7.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 2
AandB8.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 2
AandB9.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 2
AandB10.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 2
AandB11.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 3
AandB12.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 3
AandB13.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 3
AandB14.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 3
AandB15.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 3
AandB16.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 4
AandB17.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 4
AandB18.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 4
AandB19.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 4
AandB20.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 4
AandB21.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 5
AandB22.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 5
AandB23.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 5
AandB24.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 5
AandB25.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 5
  subtaskId: 5
